version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: tt-backend-dev
    restart: unless-stopped
    env_file: .env           # uses your existing .env
    ports:
      - "3000:3000"          # app
      - "9229:9229"          # node inspector
    # bind-mount code; keep container's node_modules isolated
    volumes:
      - ./:/app
      - /app/node_modules
    # if your app has a /health route, keep this; otherwise remove
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -qO- http://localhost:3000/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
